name: release
on:
  workflow_dispatch:

permissions:
  contents: write
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  create-draft:
    runs-on: ubuntu-22.04
    steps:
      - run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          ref: master

      - uses: jossef/action-set-json-field@v2.1
        with:
          file: manifest.json
          field: version
          value: ${{ env.VERSION }}

      - continue-on-error: true
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -am "release ${{github.ref_name}}"
          git push

      - run: |
          gh release create ${{github.ref_name}} -d -F CURRENT_CHANGE.md -t ${{github.ref_name}}

  windows:
    runs-on: windows-2022
    needs: create-draft
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
      - uses: actions/setup-python@v4
        id: cp310
        with:
          python-version: '3.10'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: install upx
      - run: |
          Start-BitsTransfer https://github.com/josStorer/LibreHardwareMonitor.Console/releases/download/v0.1.0/LibreHardwareMonitor.Console.zip ./LibreHardwareMonitor.Console.zip
          Expand-Archive ./LibreHardwareMonitor.Console.zip -DestinationPath ./components/LibreHardwareMonitor.Console
          Start-BitsTransfer https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip ./python-3.10.11-embed-amd64.zip
          Expand-Archive ./python-3.10.11-embed-amd64.zip -DestinationPath ./py310
          $content=Get-Content "./py310/python310._pth"; $content | ForEach-Object {if ($_.ReadCount -eq 3) {"Lib\\site-packages"} else {$_}} | Set-Content ./py310/python310._pth
          ./py310/python ./backend-python/get-pip.py
          ./py310/python -m pip install Cython==3.0.4
          Copy-Item -Path "${{ steps.cp310.outputs.python-path }}/../include" -Destination "py310/include" -Recurse
          Copy-Item -Path "${{ steps.cp310.outputs.python-path }}/../libs" -Destination "py310/libs" -Recurse
          ./py310/python -m pip install cyac==1.9
          git clone https://github.com/josStorer/ai00_rwkv_server --depth=1
          cd ai00_rwkv_server
          cargo build --release
          mv ./target/release/ai00_server.exe ../backend-rust/webgpu_server.exe
          cd ..
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          (Get-Content -Path ./backend-golang/app.go) -replace "//go:custom_build windows ", "" | Set-Content -Path ./backend-golang/app.go
          make
          Rename-Item -Path "build/bin/RWKV-Runner.exe" -NewName "RWKV-Runner_windows_x64.exe"

      - run: gh release upload ${{github.ref_name}} build/bin/RWKV-Runner_windows_x64.exe

  linux:
    runs-on: ubuntu-20.04
    needs: create-draft
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - run: |
          sudo apt-get update
          sudo apt-get install upx
          sudo apt-get install build-essential libgtk-3-dev libwebkit2gtk-4.0-dev
          git clone https://github.com/josStorer/ai00_rwkv_server --depth=1
          cd ai00_rwkv_server
          sudo apt-get install libudev-dev
          sudo apt-get install libasound2-dev
          rustup target add x86_64-unknown-linux-gnu
          cargo build --release --target x86_64-unknown-linux-gnu
          mv ./target/x86_64-unknown-linux-gnu/release/ai00_server ../backend-rust/webgpu_server
          cd ..
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          rm ./backend-python/rwkv_pip/wkv_cuda.pyd
          rm ./backend-python/rwkv_pip/rwkv5.pyd
          rm ./backend-python/rwkv_pip/beta/wkv_cuda.pyd
          rm ./backend-python/get-pip.py
          make
          mv build/bin/RWKV-Runner build/bin/RWKV-Runner_linux_x64

      - run: gh release upload ${{github.ref_name}} build/bin/RWKV-Runner_linux_x64

  macos:
    runs-on: macos-13
    needs: create-draft
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.5'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: wasm32-unknown-unknown
      - run: |
          git clone https://github.com/josStorer/ai00_rwkv_server --depth=1
          cd ai00_rwkv_server
          cargo build --release
          mv ./target/release/ai00_server ../backend-rust/webgpu_server
          cd ..
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          rm ./backend-python/rwkv_pip/wkv_cuda.pyd
          rm ./backend-python/rwkv_pip/rwkv5.pyd
          rm ./backend-python/rwkv_pip/beta/wkv_cuda.pyd
          rm ./backend-python/get-pip.py
          make
          cp build/darwin/Readme_Install.txt build/bin/Readme_Install.txt
          cp build/bin/RWKV-Runner.app/Contents/MacOS/RWKV-Runner build/bin/RWKV-Runner_darwin_universal
          cd build/bin && zip -r RWKV-Runner_macos_universal.zip RWKV-Runner.app Readme_Install.txt

      - run: gh release upload ${{github.ref_name}} build/bin/RWKV-Runner_macos_universal.zip build/bin/RWKV-Runner_darwin_universal

  publish-release:
    runs-on: ubuntu-22.04
    needs: [ windows, linux, macos ]
    steps:
      - uses: actions/checkout@v3
      - run: gh release edit ${{github.ref_name}} --draft=false
